[package]
name = "hexcede/tween"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@1.0.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"